---
enableUserTelemetry: false

dashboardReplicas: 1
operatorReplicas: 1

dataScienceCluster:
  create: true
  version: v2
  components:
    kserve:
      managementState: Managed
      nim:
        managementState: Managed
      rawDeploymentServiceConfig: Headed
    modelregistry:
      managementState: Managed
      registriesNamespace: rhoai-model-registries
    trustyai:
      managementState: Managed
    ray:
      managementState: Removed
    kueue:
      managementState: Removed
    workbenches:
      managementState: Managed
      workbenchNamespace: rhods-notebooks
    dashboard:
      managementState: Managed
    trainingoperator:
      managementState: Removed
    feastoperator: {}
    llamastackoperator:
      managementState: Removed
    ogx:
      managementState: Managed
    mlflowoperator:
      managementState: Managed
    aipipelines:
      managementState: Managed
    aigateway:
      managementState: Managed
      modelsAsAService:
        managementState: Managed
    mcplifecycleoperator:
      managementState: Managed


dataScienceClusterInitialization: 
  monitoring:
    namespace: redhat-ods-monitoring
    metrics:
      replicas: 1
      storage:
        size: 5Gi
        retention: 90d
    traces:
      sampleRatio: 0.1
      storage:
        backend: pv
        retention: 216h

acceleratorProfiles: []
hardwareProfiles: []

admins: []
userGroups:
  - system:authenticated

defaultWorkbenchPvcSize: 20Gi
showJupyterInEnabledApplications: true
notebookIdleCulling:
  enabled: true
  timeoutInMinutes: 240

modelServerSizes: null

notebookSizes: null



# CLUSTER_DOMAIN=$(oc get ingresses.config.openshift.io cluster -o jsonpath='{.spec.domain}')
# echo $CLUSTER_DOMAIN
# Use default ingress cert for HTTPS, or set CERT_NAME to your TLS secret name
# CERT_NAME=${CERT_NAME:-$(kubectl get ingresscontroller default -n openshift-ingress-operator -o jsonpath='{.spec.defaultCertificate.name}' 2>/dev/null)}
#echo $CERT_NAME

clusterDomain: needupdate
cert: needupdate