---
enableUserTelemetry: false

dashboardReplicas: 1
operatorReplicas: 1

dataScienceCluster:
  create: true
  version: v2
  components:
    kserve:
      managementState: Managed
      nim:
        managementState: Managed
      rawDeploymentServiceConfig: Headed
    modelregistry:
      managementState: Managed
      registriesNamespace: rhoai-model-registries
    trustyai:
      managementState: Managed
    ray:
      managementState: Removed
    kueue:
      managementState: Removed
    workbenches:
      managementState: Managed
      workbenchNamespace: rhods-notebooks
    dashboard:
      managementState: Managed
    trainingoperator:
      managementState: Removed
    feastoperator: {}
    llamastackoperator:
      managementState: Removed
    ogx:
      managementState: Managed
    mlflowoperator:
      managementState: Managed
    aipipelines:
      managementState: Managed
    aigateway:
      managementState: Managed
      modelsAsAService:
        managementState: Managed
    mcplifecycleoperator:
      managementState: Managed


dataScienceClusterInitialization: 
  monitoring:
    namespace: redhat-ods-monitoring
    metrics:
      replicas: 1
      storage:
        size: 5Gi
        retention: 10d
    traces:
      sampleRatio: "0.1"
      storage:
        backend: pv
        retention: 120h0m0s

acceleratorProfiles: []
hardwareProfiles: []

admins: []
userGroups:
  - system:authenticated

defaultWorkbenchPvcSize: 20Gi
showJupyterInEnabledApplications: true
notebookIdleCulling:
  enabled: true
  timeoutInMinutes: 240

modelServerSizes: null

notebookSizes: null



clusterDomain: needupdate
cert: needupdate