apiVersion: v1
kind: Secret
metadata:
  name: loki-s3-secret
  namespace: redhat-ods-monitoring
stringData:
  access_key_id: {{ .Values.s3.access_key_id }}
  access_key_secret: {{ .Values.s3.access_key_secret }}
  bucketnames: {{ .Values.s3.bucketnames }}
  endpoint: {{ .Values.s3.endpoint }}
type: Opaque
---
apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: usage
  namespace: redhat-ods-monitoring
spec:
  limits:
    global:
      otlp:
        streamLabels:
          resourceAttributes:
            - name: service.name
            - name: subscription
            - name: model
            - name: response_type
            - name: kubernetes_namespace_name
  managementState: Managed
  size: 1x.demo
  storage:
    schemas:
      - effectiveDate: "2024-10-01"
        version: v13
    secret:
      credentialMode: static
      name: loki-s3-secret
      type: s3
  storageClassName: gp3-csi
  tenants:
    mode: openshift-logging
