apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: openshift-gitops
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true,FailOnSharedResource=false
spec:
  rbac:
    defaultPolicy: ""
    policy: |
      g, system:cluster-admins, role:admin
      g, cluster-admins, role:admin
      {{- range .Values.clusterAdmins }}
      g, {{ . }}, role:admin
      {{- end }}
    # email scope is required for the per-user policy lines to match
    scopes: '[groups,email]'
