apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: openshift-gitops
data:
  policy.csv: |
    g, dieter, role:admin
    g, system:cluster-admins, role:admin
    g, cluster-admins, role:admin
