apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: rhods-admins
users:
{{- range .Values.clusterAdmins }}
- {{ . }}
{{- end }}
---
apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: cluster-admins
users:
{{- range .Values.clusterAdmins }}
- {{ . }}
{{- end }}
{{- range .Values.clusterAdmins }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ . }}-cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: {{ . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
{{- end }}
