apiVersion: v1
stringData:
  DB_CONNECTION_URL: 'postgresql://maas_user:MySuperSecretPassword123!@simple-db.redhat-ods-applications.svc.cluster.local:5432/maas?sslmode=require'
kind: Secret
metadata:
  name: maas-db-config
  namespace: redhat-ods-applications