apiVersion: stackgres.io/v1
kind: SGScript
metadata:
  name: create-maas-db-script
  namespace: redhat-ods-applications
spec:
  scripts:
    - name: create-maas-db
      script: |
        CREATE DATABASE maas;
        CREATE USER "maas_user" WITH PASSWORD 'MySuperSecretPassword123!';
        GRANT ALL PRIVILEGES ON DATABASE maas TO maas_user;
        \c maas
        GRANT ALL ON SCHEMA public TO maas_user;
---
apiVersion: stackgres.io/v1
kind: SGCluster 
metadata:
  name: simple-db
  namespace: redhat-ods-applications
spec:
  instances: 1
  postgres:
    version: '15'
  pods:
    persistentVolume:
      size: '10Gi'
  managedSql:
    scripts:
      - sgScript: create-maas-db-script
